### PR TITLE
Support ghc-9.2

### LINKED ISSUE #12: Build failure with ghc-9.2
Hello, trying to build with ghc-9.2.2 with #11 is failing with:

```
src/Json/Smile.hs:148:7: error:
    • Illegal equational constraint Control.Monad.Primitive.PrimState m
                                    ~ Exts.RealWorld
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        goComplement :: forall {m :: * -> *}.
                        (Control.Monad.Primitive.PrimState m ~ Exts.RealWorld,
                         Control.Monad.Primitive.PrimMonad m) =>
                        Int -> m ()
      In the second argument of ‘($)’, namely
        ‘do let nDigits256
                  = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
            mut <- newByteArray nDigits256
            let !(MutableByteArray mut#) = mut
            !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
            ....’
      In the expression:
        unsafeDupablePerformIO
          $ do let nDigits256
                     = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
               mut <- newByteArray nDigits256
               let !(MutableByteArray mut#) = mut
               !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
               ....
    |
148 |   let goComplement !ix = if ix >= 0
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Json/Smile.hs:156:7: error:
    • Illegal equational constraint Control.Monad.Primitive.PrimState m
                                    ~ Exts.RealWorld
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        goAddOne :: forall {m :: * -> *}.
                    (Control.Monad.Primitive.PrimState m ~ Exts.RealWorld,
                     Control.Monad.Primitive.PrimMonad m) =>
                    Int -> m ()
      In the second argument of ‘($)’, namely
        ‘do let nDigits256
                  = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
            mut <- newByteArray nDigits256
            let !(MutableByteArray mut#) = mut
            !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
            ....’
      In the expression:
        unsafeDupablePerformIO
          $ do let nDigits256
                     = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
               mut <- newByteArray nDigits256
               let !(MutableByteArray mut#) = mut
               !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
               ....
    |
156 |   let goAddOne !ix = if ix >= 0
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Would you know what is this about?

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change enables building json-syntax with ghc-9.2.

Depends-On: https://github.com/byteverse/json-syntax/pull/11
Fixes: #12

### CODE REVIEW

**Comment by andrewthad** [comment]
Can you confirm that you've been able to build with ghc 8.10, 9.0, and 9.2? This looks like it should work, but I just want to make sure that it builds.

**Comment by TristanCacqueray** [comment]
I only tested with ghc 8.10.7 and 9.2.2.

**Comment by TristanCacqueray** [comment]
HEAD is now building with ghc-9.2. Thanks!
