### ISSUE TITLE
Build failure with ghc-9.2

### ISSUE THREAD

**Issue by TristanCacqueray** [byteverse/json-syntax#12]
Hello, trying to build with ghc-9.2.2 with #11 is failing with:

```
src/Json/Smile.hs:148:7: error:
    • Illegal equational constraint Control.Monad.Primitive.PrimState m
                                    ~ Exts.RealWorld
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        goComplement :: forall {m :: * -> *}.
                        (Control.Monad.Primitive.PrimState m ~ Exts.RealWorld,
                         Control.Monad.Primitive.PrimMonad m) =>
                        Int -> m ()
      In the second argument of ‘($)’, namely
        ‘do let nDigits256
                  = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
            mut <- newByteArray nDigits256
            let !(MutableByteArray mut#) = mut
            !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
            ....’
      In the expression:
        unsafeDupablePerformIO
          $ do let nDigits256
                     = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
               mut <- newByteArray nDigits256
               let !(MutableByteArray mut#) = mut
               !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
               ....
    |
148 |   let goComplement !ix = if ix >= 0
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

src/Json/Smile.hs:156:7: error:
    • Illegal equational constraint Control.Monad.Primitive.PrimState m
                                    ~ Exts.RealWorld
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        goAddOne :: forall {m :: * -> *}.
                    (Control.Monad.Primitive.PrimState m ~ Exts.RealWorld,
                     Control.Monad.Primitive.PrimMonad m) =>
                    Int -> m ()
      In the second argument of ‘($)’, namely
        ‘do let nDigits256
                  = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
            mut <- newByteArray nDigits256
            let !(MutableByteArray mut#) = mut
            !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
            ....’
      In the expression:
        unsafeDupablePerformIO
          $ do let nDigits256
                     = fromIntegral @Word @Int (W# (GMP.sizeInBaseBigNat bn 256#))
               mut <- newByteArray nDigits256
               let !(MutableByteArray mut#) = mut
               !_ <- GMP.exportBigNatToMutableByteArray bn mut# 0## 1#
               ....
    |
156 |   let goAddOne !ix = if ix >= 0
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Would you know what is this about?

**Comment by andrewthad** [comment]
From the PR, it looks like you figured out that this just requires turns on `GADTs`.

**Comment by TristanCacqueray** [comment]
Yeah, that seems to be enough.
